export const searchSuggestions = [
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Graphic Design",
  "Logo Design",
  "Content Writing",
  "Social Media Management",
  "SEO Services",
  "Digital Marketing",
  "Video Production",
  "Copywriting",
  "Blog Writing",
  "E-commerce Development",
  "Branding Services",
  "Email Marketing",
  "PPC Advertising",
  "WordPress Development",
  "Software Development",
  "Business Plan Writing",
  "Market Research",
  "Virtual Assistant",
  "Data Entry",
  "Accounting Services",
  "Financial Consulting",
  "Product Photography",
  "3D Modeling and Rendering",
  "Illustration",
  "Mobile App Design",
  "App Testing and QA",
  "Social Media Advertising",
  "Influencer Marketing",
  "CRM Setup and Management",
  "Legal Services",
  "Video Editing",
  "Voice-over Services",
  "Animation Services",
  "PR and Media Outreach",
  "Lead Generation",
  "Business Consulting",
  "Sales Funnel Optimization",
  "Landing Page Design",
  "User Testing",
  "Market Analysis",
  "Pitch Deck Design",
  "Social Media Content Creation",
  "Data Analytics",
  "Logo Animation",
  "Chatbot Development",
  "Customer Support",
  "IT Support",
  "Mobile App Marketing",
  "App Store Optimization (ASO)",
  "Proofreading and Editing",
  "Whiteboard Animation",
  "Market Strategy",
  "Growth Hacking",
  "Influencer Outreach",
  "Customer Surveys",
  "Public Relations",
  "Bookkeeping",
  "Video Marketing",
  "Podcast Production",
  "Customer Relationship Management",
  "Blockchain Development",
  "Cybersecurity Services",
  "App Monetization",
  "Mobile App Analytics",
  "Social Media Monitoring",
  "Reputation Management",
  "Data Visualization",
  "Business Intelligence",
  "Market Entry Strategy",
  "User Experience Testing",
  "Content Strategy",
  "Infographic Design",
  "Software Integration",
  "DevOps Services",
  "Mobile App Maintenance",
  "Crowdfunding Campaigns",
  "Trade Show Booth Design",
  "Sales Training",
  "Influencer Partnerships",
  "Landing Page Optimization",
  "App Store Marketing",
  "Search Engine Marketing (SEM)",
  "Website Redesign",
  "Sales Copywriting",
  "Market Segmentation",
  "Online Advertising",
  "Chat Support",
  "Product Launch Strategy",
  "Mobile App Prototyping",
  "Business Automation",
  "CRM Integration",
  "Web Analytics",
  "Conversion Rate Optimization (CRO)",
  "Voice Search Optimization",
  "Mobile App Localization",
  "Social Media Consulting",
  "Lead Nurturing",
];

export const skillSuggestions = [
  "JavaScript",
  "Python",
  "HTML",
  "CSS",
  "React",
  "Node.js",
  "Java",
  "C++",
  "Ruby",
  "SQL",
  "PHP",
  "C#",
  "Swift",
  "Android Development",
  "iOS Development",
  "Machine Learning",
  "Data Science",
  "Artificial Intelligence",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Graphic Design",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Information Architecture",
  "Content Strategy",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "Social Media Marketing",
  "Content Marketing",
  "Email Marketing",
  "Digital Marketing",
  "Copywriting",
  "Blogging",
  "Video Editing",
  "Audio Editing",
  "Photography",
  "Videography",
  "3D Modeling",
  "Animation",
  "Illustration",
  "Motion Graphics",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "VR Development",
  "AR Development",
  "Blockchain",
  "Smart Contracts",
  "Cryptocurrency",
  "Ethereum",
  "Solidity",
  "DevOps",
  "Docker",
  "Kubernetes",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Cloud Computing",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Cybersecurity",
  "Penetration Testing",
  "Network Security",
  "Data Analysis",
  "Database Management",
  "NoSQL Databases",
  "GraphQL",
  "RESTful APIs",
  "Microservices",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Project Management",
  "Product Management",
  "Agile Project Management Tools (e.g., Jira)",
  "Version Control (e.g., Git)",
  "Linux Administration",
  "Shell Scripting",
  "Automation",
  "IoT (Internet of Things)",
  "Raspberry Pi",
  "Arduino",
  "Natural Language Processing (NLP)",
  "Chatbots",
  "TensorFlow",
  "PyTorch",
  "Computer Vision",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Microsoft Excel",
  "Mathematics",
  "Statistics",
  "Algorithms",
  "Problem Solving",
  "Critical Thinking",
  "Teamwork",
  "Communication",
  "Leadership",
  "Time Management",
  "Project Planning",
  "Customer Service",
  "Sales",
  "Negotiation",
  "Financial Analysis",
  "Budgeting",
  "Market Research",
  "Business Development",
  "Entrepreneurship",
  "Legal Knowledge",
  "Human Resources",
  "Content Management Systems (CMS)",
  "WordPress",
  "Shopify",
  "E-commerce",
  "React Native",
  "Flutter",
  "Vue.js",
  "Angular",
  "Meteor",
  "Express.js",
  "Ruby on Rails",
  "Spring Framework",
  "Django",
  "Flask",
  "Laravel",
  "Symfony",
  "WordPress Development",
  "Magento",
  "WooCommerce",
  "Shopify Development",
  "Big Data",
  "Hadoop",
  "Spark",
  "Data Warehousing",
  "ETL (Extract, Transform, Load)",
  "UI/UX Prototyping Tools (e.g., Sketch, Figma)",
  "Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
  "Video Production Software (e.g., Adobe Premiere Pro, Final Cut Pro)",
  "Audio Editing Software (e.g., Adobe Audition, GarageBand)",
  "3D Modeling Software (e.g., Blender, Maya)",
  "Game Engines (e.g., Unreal Engine, Unity)",
  "Blockchain Development Platforms (e.g., Ethereum, Binance Smart Chain)",
  "Continuous Integration/Continuous Deployment (CI/CD) Tools (e.g., Jenkins, Travis CI)",
  "Web Hosting Services (e.g., Bluehost, HostGator)",
  "Container Orchestration Tools (e.g., Docker Swarm)",
  "Frontend Frameworks (e.g., AngularJS, Ember.js)",
  "Backend Frameworks (e.g., Express.js, Ruby on Rails)",
  "Version Control Systems (e.g., SVN, Mercurial)",
  "Database Management Systems (e.g., MySQL, PostgreSQL)",
  "Data Science Libraries (e.g., Pandas, NumPy)",
  "Testing Frameworks (e.g., Jest, Selenium)",
  "Cybersecurity Tools (e.g., Wireshark, Nmap)",
  "Data Visualization Tools (e.g., D3.js, Matplotlib)",
  "Cloud Computing Platforms (e.g., IBM Cloud, Oracle Cloud)",
  "Code Editors (e.g., Visual Studio Code, Sublime Text)",
  "Integrated Development Environments (IDEs) (e.g., IntelliJ IDEA, PyCharm)",
  "Text Editors (e.g., Vim, Emacs)",
  "Markdown",
  "Technical Writing",
  "Remote Collaboration Tools (e.g., Zoom, Slack)",
  "Agile Project Management Methodologies (e.g., Scrum, Kanban)",
  "Machine Learning Frameworks (e.g., Keras, Scikit-learn)",
  "Web Design Principles",
  "Database Design",
  "Network Administration",
  "Virtualization",
  "Linux Command Line",
  "Cloud Security",
  "Shell Scripting",
  "API Documentation",
  "Frontend Performance Optimization",
  "Backend Performance Optimization",
  "Data Warehousing",
  "Serverless Architecture",
  "Blockchain Development",
  "AR/VR Development",
  "Game Design",
  "Data Engineering",
  "Bioinformatics",
  "Biohacking",
  "Ethical Hacking",
  "Robotic Process Automation",
  "Motion Design",
  "UI/UX Animation",
  "Chatbot Development",
  "Conversational AI",
  "Quantum Computing",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Natural Language Generation (NLG)",
  "Edge Computing",
  "Quantum Machine Learning",
];
